### ISSUE TITLE
Add a type of `Source` that can be initialized with ETM data

### ISSUE THREAD

**Issue by noracato** [quintel/meurit-py#19]
Right now `Source` reads csv's from a specific location, but we also need a type of `Source` that can extract the correct merit order information from an ETM scenario, and transform that into input data for `MeritOrder`.

We can use [pyETM](https://github.com/robcalon/PyETM) to help us with the ETM connection.

### Todo's
- [ ] If not yet done, add `pyetm` to the Pipfile
- [ ] Find out what information we should extract from the ETM, and which endpoints are neccesary. We might need Atlas as well (hope not).
- [ ] Define the neccesary transformations to ready this data
- [ ] Build this new type of Source, extracting, transforming and readying the ETM data
