### ISSUE TITLE
Use pyETM to communicate results back to ETM

### ISSUE THREAD

**Issue by noracato** [quintel/meurit-py#9]
Countries should have a method that communicates their end results back to the ETM. These results include a price curve and an availability curve per interconnector.

### Prerequisites
- [ ] Make sure the `pyETM` module is able to upload availability curves
- [ ] Make sure Merit + ETEngine support availability curves

### Todo's
- [ ] Include the [`pyETM`](https://github.com/robcalon/PyETM) module to use for ETM communication
- [ ] Create `export_to_etm` method on Country
- [ ] Communicate errors etc to user
